spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dabai-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-dabai-test
# 保存为UTF-8